"""empty message

Revision ID: 2ab316add67b
Revises: b8fbd8684486
Create Date: 2020-12-23 22:13:55.410384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab316add67b'
down_revision = 'b8fbd8684486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'artist_image_link')
    # ### end Alembic commands ###
