"""empty message

Revision ID: 58147761c5d2
Revises: c4a42d99074d
Create Date: 2020-12-23 01:17:09.496827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58147761c5d2'
down_revision = 'c4a42d99074d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'seekinng_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seekinng_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
