"""empty message

Revision ID: 745b70ceaf31
Revises: bd634be9d18e
Create Date: 2020-12-17 17:04:05.714469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745b70ceaf31'
down_revision = 'bd634be9d18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues_genres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seekinng_description', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seekinng_description')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_table('venues_genres')
    # ### end Alembic commands ###
