"""empty message

Revision ID: c4a42d99074d
Revises: dea4db7288d5
Create Date: 2020-12-22 00:43:42.343618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a42d99074d'
down_revision = 'dea4db7288d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'seekinng_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seekinng_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
